/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tooth.glb --transform 
Files: tooth.glb [15.15MB] > C:\Users\9\Desktop\zub-clinik\tooth\tooth-transformed.glb [501.76KB] (97%)
Author: Vikrama Raghuraman (https://sketchfab.com/vikrama1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/molar-tooth-54376b4e2c3b4091aedaa12d94e15076
Title: Molar Tooth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tooth-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} scale={[1, 1, 1.249]} />
    </group>
  )
}

useGLTF.preload('/tooth-transformed.glb')
